USE [BD_PLANTILLA_PRD]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Fields](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_Template] [int] NULL,
	[Nombre_Campo] [nvarchar](100) NULL,
	[Tipo_Campo] [nvarchar](20) NULL,
	[Cord_x] [float] NOT NULL,
	[Cord_y] [float] NOT NULL,
	[Cord_width] [float] NOT NULL,
	[Cord_height] [float] NOT NULL,
	[NroPagina] [int] NOT NULL,
	[IdRectangulo] [int] NOT NULL,
 CONSTRAINT [PK__Tbl_Fiel__3214EC2756BF2857] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Template](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](max) NULL,
	[Xmp] [nvarchar](max) NULL,
	[Imagen] [nvarchar](max) NULL,
	[ID_Grado] [int] NULL,
 CONSTRAINT [PK__Tbl_Temp__3214EC27F19AECE0] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tbl_Fields]  WITH CHECK ADD  CONSTRAINT [FK__Tbl_Field__ID_Te__21B6055D] FOREIGN KEY([ID_Template])
REFERENCES [dbo].[Tbl_Template] ([ID])
GO
ALTER TABLE [dbo].[Tbl_Fields] CHECK CONSTRAINT [FK__Tbl_Field__ID_Te__21B6055D]
GO
ALTER TABLE [dbo].[Tbl_Template]  WITH CHECK ADD  CONSTRAINT [FK__Tbl_Templ__ID_Gr__245D67DE] FOREIGN KEY([ID_Grado])
REFERENCES [dbo].[Tbl_Grado] ([ID])
GO
ALTER TABLE [dbo].[Tbl_Template] CHECK CONSTRAINT [FK__Tbl_Templ__ID_Gr__245D67DE]
GO
